<?php

namespace App\Http\Requests\Admin\Post;

use Illuminate\Foundation\Http\FormRequest;

class StoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'title'=>'required|string',
            'content'=>'required|string',
            'preview_image'=>'required|file',
            'main_image'=>'required|file',
            'category_id'=>'required|integer|exists:categories,id',
            'tag_ids'=>'nullable|array',
            'tag_id.*'=>'nullable|integer|exists:tags,id'
        ];
    }

    public function messages()
    {
       // return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'title.required'=>'Це поле необхідно для заповнення',
            'title.string'=>'Необхідно ввести иекс до 250 символів',
            'content.required'=>'Це поле необхідно для заповнення',
            'content.string'=>'Необхідно ввести иекс до 250 символів',
            'preview_image.required'=>'Необхідно вибрати файл з зображенням',
            'main_image.required'=>'Необхідно вибрати файл з зображенням',
        ];
    }
}
