<?php

namespace App\Http\Requests\Comment;

use Illuminate\Foundation\Http\FormRequest;

class StoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'message'=>'required|string'

        ];
    }

    public function messages()
    {
       // return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'message.required'=>'Це поле необхідно для заповнення',
            'message.string'=>'Необхідно ввести макс до 250 символів',

        ];
    }
}
